bits 64

%macro THUNK 1
global %1:function
align 16
%1:
invlpg [rax]
db %str(%1), 0
ret
%endmacro

%macro INTERFACE_NAME 1
%1 %+ _name:
db %str(%1), 0
%endmacro

%macro INTERFACE_ENTRY 1
dq %1 %+ _name
dq %1
%endmacro

section .data

extern wl_output_interface
extern wl_shell_interface
extern wl_shell_surface_interface
extern wl_display_interface
extern wl_touch_interface
extern wl_subsurface_interface
extern wl_subcompositor_interface
extern wl_shm_pool_interface
extern wl_pointer_interface
extern wl_compositor_interface
extern wl_shm_interface
extern wl_registry_interface
extern wl_buffer_interface
extern wl_seat_interface
extern wl_surface_interface
extern wl_keyboard_interface
extern wl_callback_interface
extern wl_region_interface
extern wl_data_device_interface
extern wl_data_source_interface
extern wl_data_offer_interface
extern wl_data_device_manager_interface

INTERFACE_NAME wl_display_interface
INTERFACE_NAME wl_output_interface
INTERFACE_NAME wl_shell_interface
INTERFACE_NAME wl_shell_surface_interface
INTERFACE_NAME wl_touch_interface
INTERFACE_NAME wl_subsurface_interface
INTERFACE_NAME wl_subcompositor_interface
INTERFACE_NAME wl_shm_pool_interface
INTERFACE_NAME wl_pointer_interface
INTERFACE_NAME wl_compositor_interface
INTERFACE_NAME wl_shm_interface
INTERFACE_NAME wl_registry_interface
INTERFACE_NAME wl_buffer_interface
INTERFACE_NAME wl_seat_interface
INTERFACE_NAME wl_surface_interface
INTERFACE_NAME wl_keyboard_interface
INTERFACE_NAME wl_callback_interface
INTERFACE_NAME wl_region_interface
INTERFACE_NAME wl_data_device_interface
INTERFACE_NAME wl_data_source_interface
INTERFACE_NAME wl_data_offer_interface
INTERFACE_NAME wl_data_device_manager_interface

libname:
db "libwayland-client.so", 0

section .text

global __felix86_constructor:function
align 16
__felix86_constructor:
invlpg [rbx]
ret
dd 0x12345678 ; invlpg + ret are 4 bytes, four more here to align to pointer
dd constructor_data - ($ + 4) ; RIP-relative offset to data table (avoids TEXTREL)

section .data
align 8
constructor_data:
dq libname
; the constructor will set these to the host libwayland-client pointers
INTERFACE_ENTRY wl_output_interface
INTERFACE_ENTRY wl_display_interface
INTERFACE_ENTRY wl_shell_interface
INTERFACE_ENTRY wl_shell_surface_interface
INTERFACE_ENTRY wl_touch_interface
INTERFACE_ENTRY wl_subsurface_interface
INTERFACE_ENTRY wl_subcompositor_interface
INTERFACE_ENTRY wl_shm_pool_interface
INTERFACE_ENTRY wl_pointer_interface
INTERFACE_ENTRY wl_compositor_interface
INTERFACE_ENTRY wl_shm_interface
INTERFACE_ENTRY wl_registry_interface
INTERFACE_ENTRY wl_buffer_interface
INTERFACE_ENTRY wl_seat_interface
INTERFACE_ENTRY wl_surface_interface
INTERFACE_ENTRY wl_keyboard_interface
INTERFACE_ENTRY wl_callback_interface
INTERFACE_ENTRY wl_region_interface
INTERFACE_ENTRY wl_data_device_interface
INTERFACE_ENTRY wl_data_source_interface
INTERFACE_ENTRY wl_data_offer_interface
INTERFACE_ENTRY wl_data_device_manager_interface
dq 0
dq 0

section .text

THUNK wl_display_connect
THUNK wl_display_flush
THUNK wl_display_cancel_read
THUNK wl_display_create_queue
THUNK wl_display_disconnect
THUNK wl_display_dispatch
THUNK wl_display_dispatch_pending
THUNK wl_display_dispatch_queue
THUNK wl_display_dispatch_queue_pending
THUNK wl_display_get_error
THUNK wl_display_prepare_read
THUNK wl_display_prepare_read_queue
THUNK wl_display_read_events
THUNK wl_display_roundtrip
THUNK wl_display_roundtrip_queue
THUNK wl_display_connect_to_fd
THUNK wl_display_get_fd
THUNK wl_display_create_queue_with_name
THUNK wl_display_dispatch_timeout
THUNK wl_display_dispatch_queue_timeout
THUNK wl_display_set_max_buffer_size
THUNK wl_event_queue_destroy
THUNK wl_event_queue_get_name
THUNK wl_proxy_add_listener
THUNK wl_proxy_create
THUNK wl_proxy_destroy
THUNK wl_proxy_create_wrapper
THUNK wl_proxy_get_class
THUNK wl_proxy_get_id
THUNK wl_proxy_get_listener
THUNK wl_proxy_get_tag
THUNK wl_proxy_get_user_data
THUNK wl_proxy_get_version
THUNK wl_proxy_set_queue
THUNK wl_proxy_get_queue
THUNK wl_proxy_get_display
THUNK wl_proxy_set_tag
THUNK wl_proxy_set_user_data
THUNK wl_proxy_wrapper_destroy
THUNK wl_proxy_marshal_array
THUNK wl_proxy_marshal_array_constructor
THUNK wl_proxy_marshal_array_constructor_versioned
THUNK wl_proxy_marshal_array_flags
THUNK wl_list_init
THUNK wl_list_insert
THUNK wl_list_remove
THUNK wl_list_length
THUNK wl_list_empty
THUNK wl_list_insert_list

global wl_log_set_handler_client:function
align 16
wl_log_set_handler_client:
; TODO: callback stuff...
ret

section .init_array
    dq __felix86_constructor

section .note.GNU-stack noalloc noexec nowrite progbits
