#include "fex_test_loader.hpp"

// We have some tests that are not part of the FEX project, but use the same infrastructure
#define BUG_TEST(name)                                                                                                                               \
    CATCH_TEST_CASE(#name, "[felix86_bugs]") {                                                                                                       \
        FEXTestLoader::RunTest("ASM/felix86_bugs/" #name ".asm");                                                                                    \
    }

#define FEX_BUG_TEST(name)                                                                                                                           \
    CATCH_TEST_CASE(#name, "[felix86_bugs]") {                                                                                                       \
        FEXTestLoader::RunTest("ASM/FEX_bugs/" #name ".asm");                                                                                        \
    }

BUG_TEST(32bit_syscall.asm)
BUG_TEST(BEXTR_flags.asm)
BUG_TEST(BLSI_flags.asm)
BUG_TEST(BLSMSK_flags.asm)
BUG_TEST(BLSR_flags.asm)
BUG_TEST(BZHI_Sign.asm)
BUG_TEST(IMUL_garbagedata_negative.asm)
BUG_TEST(LargeRotatesForSmallSizes.asm)
BUG_TEST(LargeRotatesForSmallSizes_More.asm)
BUG_TEST(LongSignedDivide.asm)
BUG_TEST(LoopAddressSizeCheck.asm)
BUG_TEST(MinMaxNaN.asm)
BUG_TEST(NegativeCallAddressSizeOverride.asm)
BUG_TEST(PSRLDQBuf.asm)
BUG_TEST(Push.asm)
BUG_TEST(RegCacheMMX.asm)
BUG_TEST(SBCSmall.asm)
BUG_TEST(SHRD_OF.asm)
BUG_TEST(SIBScaleTranspose.asm)
BUG_TEST(SegmentAddressOverride.asm)
BUG_TEST(ShiftConstantBug.asm)
BUG_TEST(ShiftPF.asm)
BUG_TEST(ShiftZeroFlagsUpdate.asm)
BUG_TEST(SmallShiftFlags.asm)
BUG_TEST(Test_CmpSelect_Merge.asm)
BUG_TEST(Test_CmpSelect_Merge_Float.asm)
BUG_TEST(Test_CmpSelect_Merge_Float_branch.asm)
BUG_TEST(Test_CmpSelect_Merge_branch.asm)
BUG_TEST(Test_JP.asm)
BUG_TEST(Test_PF_Zero_Shift.asm)
BUG_TEST(TrickyRA.asm)
BUG_TEST(UnalignedLoadStoreSIGBUS.asm)
BUG_TEST(VectorLoadCrash.asm)
BUG_TEST(VectorShift_zero.asm)
BUG_TEST(VectorShift_zero_256.asm)
BUG_TEST(VectorShift_zero_avx_128.asm)
BUG_TEST(XeSS_quadratic.asm)
BUG_TEST(adcx_size.asm)
BUG_TEST(add_sub_carry.asm)
BUG_TEST(add_sub_carry_2.asm)
BUG_TEST(mmx_x87_register_conflating.asm)
BUG_TEST(mov_address_size_override.asm)
BUG_TEST(nzcv_implicit_clobber.asm)
BUG_TEST(nzcv_rmw.asm)
BUG_TEST(nzcv_spill_enderlilies.asm)
BUG_TEST(overlapping_memcpy_bug.asm)
BUG_TEST(pcmpestri_garbage_rcx.asm)
BUG_TEST(repeat_on_incdec.asm)
BUG_TEST(repeat_stringops_crash.asm)
BUG_TEST(rotate_zero_extend_with_zero.asm)
BUG_TEST(sbbNZCVBug.asm)
BUG_TEST(smallvectorload_regreg.asm)
BUG_TEST(vcvtdq2ps_incorrect_size.asm)
BUG_TEST(vgather_xmm4.asm)
BUG_TEST(vmov_size_test.asm)
BUG_TEST(x87_integer_indefinite.asm)
BUG_TEST(xor_flags.asm)
BUG_TEST(dl_aux_init_stuck)
BUG_TEST(bsr_reg)
BUG_TEST(regalloc_overload)
BUG_TEST(ssa_phi_bug)
BUG_TEST(add8_lock)
BUG_TEST(cmpxchg64_lock)
BUG_TEST(strlen_sse2)
BUG_TEST(pmovmskb)
BUG_TEST(cfmerge)
BUG_TEST(test_high)
BUG_TEST(bt_jc)
BUG_TEST(movd)
BUG_TEST(bts)
BUG_TEST(llvmpipe_rast_triangle)
BUG_TEST(packsswb)
BUG_TEST(adc)
BUG_TEST(why)
BUG_TEST(fpu_stack)
BUG_TEST(bswap_word)
BUG_TEST(atomic_and)
BUG_TEST(full_vperm2i128)
BUG_TEST(full_vperm2i128_zero_low)
BUG_TEST(full_vperm2i128_zero_high)
// BUG_TEST(crc_simple)
// BUG_TEST(ror_clearof)
