#include "fex_test_loader.hpp"

// We have some tests that are not part of the FEX project, but use the same infrastructure
#define BUG_TEST(name)                                                                                                                               \
    CATCH_TEST_CASE(#name, "[felix86_bugs]") {                                                                                                       \
        FEXTestLoader::RunTest("ASM/felix86_bugs/" #name ".asm");                                                                                    \
    }

#define FEX_BUG_TEST(name)                                                                                                                           \
    CATCH_TEST_CASE(#name, "[felix86_bugs]") {                                                                                                       \
        FEXTestLoader::RunTest("ASM/FEX_bugs/" #name ".asm");                                                                                        \
    }

BUG_TEST(32bit_syscall)
BUG_TEST(BEXTR_flags)
BUG_TEST(BLSI_flags)
BUG_TEST(BLSMSK_flags)
BUG_TEST(BLSR_flags)
BUG_TEST(BZHI_Sign)
BUG_TEST(IMUL_garbagedata_negative)
BUG_TEST(LargeRotatesForSmallSizes)
BUG_TEST(LargeRotatesForSmallSizes_More)
BUG_TEST(LongSignedDivide)
BUG_TEST(LoopAddressSizeCheck)
BUG_TEST(MinMaxNaN)
BUG_TEST(NegativeCallAddressSizeOverride)
BUG_TEST(PSRLDQBuf)
BUG_TEST(Push)
BUG_TEST(RegCacheMMX)
BUG_TEST(SBCSmall)
BUG_TEST(SHRD_OF)
BUG_TEST(SIBScaleTranspose)
BUG_TEST(SegmentAddressOverride)
BUG_TEST(ShiftConstantBug)
BUG_TEST(ShiftPF)
BUG_TEST(ShiftZeroFlagsUpdate)
BUG_TEST(SmallShiftFlags)
BUG_TEST(Test_CmpSelect_Merge)
BUG_TEST(Test_CmpSelect_Merge_Float)
BUG_TEST(Test_CmpSelect_Merge_Float_branch)
BUG_TEST(Test_CmpSelect_Merge_branch)
BUG_TEST(Test_JP)
BUG_TEST(Test_PF_Zero_Shift)
BUG_TEST(TrickyRA)
BUG_TEST(UnalignedLoadStoreSIGBUS)
BUG_TEST(VectorLoadCrash)
BUG_TEST(VectorShift_zero)
BUG_TEST(VectorShift_zero_256)
BUG_TEST(VectorShift_zero_avx_128)
BUG_TEST(XeSS_quadratic)
BUG_TEST(adcx_size)
BUG_TEST(add_sub_carry)
BUG_TEST(add_sub_carry_2)
BUG_TEST(mmx_x87_register_conflating)
BUG_TEST(mov_address_size_override)
BUG_TEST(nzcv_implicit_clobber)
BUG_TEST(nzcv_rmw)
BUG_TEST(nzcv_spill_enderlilies)
BUG_TEST(overlapping_memcpy_bug)
BUG_TEST(pcmpestri_garbage_rcx)
BUG_TEST(repeat_on_incdec)
BUG_TEST(repeat_stringops_crash)
BUG_TEST(rotate_zero_extend_with_zero)
BUG_TEST(sbbNZCVBug)
BUG_TEST(smallvectorload_regreg)
BUG_TEST(vcvtdq2ps_incorrect_size)
BUG_TEST(vgather_xmm4)
BUG_TEST(vmov_size_test)
BUG_TEST(x87_integer_indefinite)
BUG_TEST(xor_flags)
BUG_TEST(dl_aux_init_stuck)
BUG_TEST(bsr_reg)
BUG_TEST(regalloc_overload)
BUG_TEST(ssa_phi_bug)
BUG_TEST(add8_lock)
BUG_TEST(cmpxchg64_lock)
BUG_TEST(strlen_sse2)
BUG_TEST(pmovmskb)
BUG_TEST(cfmerge)
BUG_TEST(test_high)
BUG_TEST(bt_jc)
BUG_TEST(movd)
BUG_TEST(bts)
BUG_TEST(llvmpipe_rast_triangle)
BUG_TEST(packsswb)
BUG_TEST(adc)
BUG_TEST(why)
BUG_TEST(fpu_stack)
BUG_TEST(bswap_word)
BUG_TEST(atomic_and)
BUG_TEST(full_vperm2i128)
BUG_TEST(full_vperm2i128_zero_low)
BUG_TEST(full_vperm2i128_zero_high)
// BUG_TEST(crc_simple)
// BUG_TEST(ror_clearof)
