name: Build
on:
  push:
    branches:
      - master
    tags:
      - '[0-9][0-9].[0-9][0-9]'
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ccache gcc-riscv64-linux-gnu g++-riscv64-linux-gnu libglx-dev libgl-dev libvulkan-dev libwayland-dev libx11-dev nasm
          # Please somebody fix riscv.cmake and make it include /usr/include thanks
          sudo cp -r /usr/include/GL /usr/local/include/GL
          sudo cp -r /usr/include/vulkan /usr/local/include/vulkan
          sudo cp -r /usr/include/X11 /usr/local/include/X11
          sudo cp -r /usr/include/KHR /usr/local/include/KHR
          sudo cp -r /usr/include/vk_video /usr/local/include/vk_video
      - name: Configure
        run: |
          EXTRA_FLAGS=""
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            EXTRA_FLAGS="-DFELIX86_MONTHLY_RELEASE=1"
          fi
          cmake -B ${{ github.workspace }}/build -DBUILD_TESTS=1 -DCMAKE_TOOLCHAIN_FILE=riscv.cmake -DFELIX86_BUILD_THUNKING=1 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release $EXTRA_FLAGS
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build -j$(nproc)
      - name: Configure thunk libs
        run: |
          cmake -S ${{ github.workspace }}/src/felix86/hle/guest_libs -B ${{ github.workspace }}/src/felix86/hle/guest_libs/build
      - name: Build thunk libs
        run: |
          cmake --build ${{ github.workspace }}/src/felix86/hle/guest_libs/build -j$(nproc)
      - name: Prepare artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          mkdir -p ${{ github.workspace }}/artifact/lib
          cp ${{ github.workspace }}/build/felix86 ${{ github.workspace }}/artifact/
          mv ${{ github.workspace }}/src/felix86/hle/guest_libs/build/x86_64-linux-gnu ${{ github.workspace }}/artifact/lib
          mkdir -p ${{ github.workspace }}/test
          cp ${{ github.workspace }}/build/felix86_test ${{ github.workspace }}/test/
          cp ${{ github.workspace }}/build/felix86 ${{ github.workspace }}/test/
          cp -r ${{ github.workspace }}/build/ASM ${{ github.workspace }}/test/
          cp -r ${{ github.workspace }}/build/32Bit_ASM ${{ github.workspace }}/test/
          cp -r ${{ github.workspace }}/build/Binaries ${{ github.workspace }}/test/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux_artifact
          path: ${{ github.workspace }}/artifact
      - name: Upload test binary
        uses: actions/upload-artifact@v4
        with:
          name: test_artifact
          path: ${{ github.workspace }}/test
          retention-days: 1
  test:
    needs: build
    runs-on: bpi-f3
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v5
        with:
          name: linux_artifact
          path: ${{ github.workspace }}/artifact
      - name: Download test artifact
        uses: actions/download-artifact@v5
        with:
          name: test_artifact
          path: ${{ github.workspace }}/test
      - name: Test
        run: |
          # We don't update the binfmt_misc installation so don't use it while running tests
          export FELIX86_BINFMT_MISC_INSTALLED=0
          chmod +x ${{ github.workspace }}/test/felix86_test
          chmod +x ${{ github.workspace }}/test/felix86
          ${{ github.workspace }}/test/felix86_test
          ${{ github.workspace }}/test/felix86 -k
          FELIX86PATH="${{ github.workspace }}/test/felix86"
          ROOTFSPATH=$($FELIX86PATH -g)
          git clone https://github.com/felix86-emu/binary_tests $RUNNER_TEMP/tests
          cd $RUNNER_TEMP/tests
          bash ./install-tests.sh $ROOTFSPATH/$HOME/felix86_test_binaries
          bash ./run-tests.sh $FELIX86PATH $ROOTFSPATH/$HOME/felix86_test_binaries

