name: Instruction Counter
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libxbyak-dev
      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -DBUILD_INSTRUCTION_COUNTER=ON -DFELIX86_BUILD_THUNKING=OFF -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target felix86_instruction_counter -j$(nproc)
      - name: Run instruction counter
        run: ${{ github.workspace }}/build/felix86_instruction_counter
      - name: Check for differences
        run: git diff --exit-code counts/
