name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: bpi-f3
    steps:
      - name: Download Foo binary
        uses: actions/download-artifact@v4
        with:
          name: Linux executable
          path: ./artifact
      - name: Test
        run: |
          FELIX86_ALL_EXTENSIONS=g,v,b ./artifact/felix86_test
          ./artifact/felix86 -k
          FELIX86_ALL_EXTENSIONS=g,v ./artifact/felix86_test
          ./artifact/felix86 -k
